name: wave_blob
description: This package provide a blob wave animation that can be customized to your needs. You can playing audio using amplitude of voice.
version: 1.0.5
repository: https://github.com/hosein-nadali/flutter-wave-blob/
homepage: https://github.com/hosein-nadali/flutter-wave-blob/

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
